### ISSUE TITLE
Have you looked at how SwiftUI implements MVVM?

### ISSUE THREAD

**Issue by saad-palapa** [buttonsrtoys/mvvm_plus#32]
Before moving to Flutter, I prototyped my app with SwiftUI.

SwiftUI was built with MVVM from the start. It's beautifully done and I would love to see some of its features in this implementation.

Take a look at this [Stanford course](https://youtu.be/--qKOhdgJAs) for a good introduction. I would love to hear your opinion.

**Comment by buttonsrtoys** [comment]
Thanks for the message. I'm happy to share some opinions and just read a couple articles on SwiftUI. (I didn't watch the vid because its 93 minutes long.) SwiftUI and MVVM+ are both straight implementations of MVVM. E.g., they both implement Views, ViewModels and data binding. Is there feature in SwitchUI in particular that you are looking for?
